spring:

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/storeManager?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

    defer-datasource-initialization: true
    open-in-view: false
    show-sql: true
  mvc:
    hidden-method:
      filter:
        enabled: true
